image: eugenmayer/make

stages:
    - build
    - test

build:
    stage: build
    script:
        - rm -rf rules bin src/main/resources/antlr
        - cd antlr_config && ./antlrBuild
        - find src/main/resources/ -name '*.java' > $@
        - mkdir bin
        - java javac @$@
        - ./gradlew build

test:
    script:
        - echo "This should print Hello World for now"
        - ./gradlew run
