stages:
    - build
    - test

build:
    stage: build
    script:
        - apt-get install build-essential -y --no-install-recommends
        - make clean
        - make

test:
    script:
        - echo "This should print Hello World for now"
        - ./gradlew run
