image: alexusher/wacc:latest

stages:
    - build
    - semantic

build:
    stage: build
    script:
        - make clean && make

semantic:
    script:
        - make
        - ./gradlew semanticTests
