image: alexusher/wacc:latest

stages:
    - build
    - testlocal
    - test
    - testExecution

build:
    stage: build
    script:
        - make clean && make

testSemantic:
    script:
        - make
        - ./gradlew semanticTests

testError:
    script:
        - make
        - ./gradlew errorTests

testGraphs:
    script:
        - make
        - ./gradlew graphTests

test:
    script:
        - make
        - ./gradlew executionTests
    only:
        - master

