image: alexusher/wacc:latest

stages:
    - build
    - testlocal
    - test
    - testExecution

build:
    stage: build
    script:
        - make clean && make

testlocal:
    script:
        - make
        - cd compiler && ./gradlew semanticTests

test:
    script:
        - make
        - cd compiler && ./gradlew errorTests

testExecution:
    script:
        - make
        - cd compiler && ./gradlew executionTests

