image: alexusher/wacc:latest

stages:
    - build
    - testlocal
    - test

build:
    stage: build
    script:
        - make clean && make

testlocal:
    script:
        - make
        - ./gradlew semanticTests
    only:
        - master

test:
    script:
        - make
        - ./gradlew errorTests
    only:
        - master