image: alexusher/wacc:latest

stages:
    - build
    - semantic_test

build:
    stage: build
    script:
        - make clean && make

semantic_test:
    script:
        - make
        - ./gradlew semanticTests
    only: 
        - master
