image: alexusher/wacc:latest

stages:
    - build
    - testlocal
    - test
    - testExecution

build:
    stage: build
    script:
        - make clean && make

testlocal:
    script:
        - make
        - ./gradlew semanticTests

test:
    script:
        - make
        - ./gradlew errorTests

testExecution:
    script:
        - make
        - ./gradlew executionTests
    only:
        - master

